version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8900:80"
      - "9900:443"
    
  financeDatabase:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
        SA_PASSWORD: "DiLb984ImW"
        ACCEPT_EULA: "Y"
        MSSQL_AGENT_ENABLED: "true"
    ports:
        - "1435:1433" 
    container_name: financeDatabase
    volumes:
        - "./Finance-db-data:/var/opt/mssql/data"


volumes: 
  db-data: